import { NextResponse } from "next/server";
import { getClaimById, setClaimTag } from "@/database/queries";
import { generateText } from "ai";
import { mistral } from "@ai-sdk/mistral";
import { ALLOWED_TAGS } from "@/constants/tags.js";

export async function POST(request, { params }) {
  try {
    const resolvedParams = await params;
    const claimId = parseInt(resolvedParams.id);

    if (isNaN(claimId)) {
      return NextResponse.json({ error: "Invalid claim ID" }, { status: 400 });
    }

    // 1. récupérer la claim
    const claim = await getClaimById(claimId);

    if (!claim) {
      return NextResponse.json({ error: "Claim not found" }, { status: 404 });
    }

    const categories = ALLOWED_TAGS.map(tag => `- ${tag}`).join('\n');

    // 2. appel LLM
    const result = await generateText({
      model: mistral("mistral-small-latest"),
      prompt: `
		You are a financial complaint classification assistant.

		Your task is to classify the following customer complaint into EXACTLY ONE of these categories:

		${categories}

		Rules:
		- Respond with ONLY the exact category name.
		- Do not explain your answer.
		- Do not add punctuation.
		- Do not invent new categories.
		- Choose the closest matching category from the list.

		Customer complaint:
		${claim.content}
      `,
    });
    const generatedTag = result.text.trim();

    const tag = ALLOWED_TAGS.find(
		(allowed) =>
		allowed.toLowerCase() === generatedTag.toLowerCase()
    );

   if (!tag) {
	return NextResponse.json(
	{ error: "Invalid tag generated by AI" },
	{ status: 500 }
	);
   }

    // 3. sauvegarde en base
    await setClaimTag(claimId, tag);

    // 4. réponse
    return NextResponse.json({ tag });
  } catch (error) {
    console.error("Auto-tag error:", error);

    return NextResponse.json(
      { error: error.message || "LLM service error" },
      { status: 500 }
    );
  }
}