// import { NextResponse } from "next/server";
// import { getClaimById, setClaimTag } from "@/database/queries";
// import { generateText } from "ai";
// import { mistral } from "@ai-sdk/mistral";
// import { ALLOWED_TAGS } from "@/constants/tags.js";

// export async function POST(request, { params }) {
//   try {
//     const resolvedParams = await params;
//     const claimId = parseInt(resolvedParams.id);

//     if (isNaN(claimId)) {
//       return NextResponse.json({ error: "Invalid claim ID" }, { status: 400 });
//     }

//     // 1. récupérer la claim
//     const claim = await getClaimById(claimId);

//     if (!claim) {
//       return NextResponse.json({ error: "Claim not found" }, { status: 404 });
//     }

//     const categories = ALLOWED_TAGS.map(tag => `- ${tag}`).join('\n');

//     // 2. appel LLM
//     const result = await generateText({
//       model: mistral("mistral-small-latest"),
//       prompt: `
// 		You are a financial complaint classification assistant.

// 		Your task is to classify the following customer complaint into EXACTLY ONE of these categories:

// 		${categories}

// 		Rules:
// 		- Respond with ONLY the exact category name.
// 		- Do not explain your answer.
// 		- Do not add punctuation.
// 		- Do not invent new categories.
// 		- Choose the closest matching category from the list.

// 		Customer complaint:
// 		${claim.content}
//       `,
//     });
//     const generatedTag = result.text.trim();

//     const tag = ALLOWED_TAGS.find(
// 		(allowed) =>
// 		allowed.toLowerCase() === generatedTag.toLowerCase()
//     );

//    if (!tag) {
// 	return NextResponse.json(
// 	{ error: "Invalid tag generated by AI" },
// 	{ status: 500 }
// 	);
//    }

//     // 3. sauvegarde en base
//     await setClaimTag(claimId, tag);

//     // 4. réponse
//     return NextResponse.json({ tag });
//   } catch (error) {
//     console.error("Auto-tag error:", error);

//     return NextResponse.json(
//       { error: error.message || "LLM service error" },
//       { status: 500 }
//     );
//   }
// }

import { NextResponse } from "next/server";

import {
  getClaimById,
  setClaimTag
} from "@/database/queries";

import { ALLOWED_TAGS } from "@/constants/tags.js";


// ======================================================
// AUTO TAG ROUTE
// ======================================================

export async function POST(request, { params }) {

  try {

    // ==================================================
    // CLAIM ID
    // ==================================================

    const resolvedParams = await params;

    const claimId = parseInt(resolvedParams.id);

    if (isNaN(claimId)) {

      return NextResponse.json(
        { error: "Invalid claim ID" },
        { status: 400 }
      );
    }

    // ==================================================
    // GET CLAIM
    // ==================================================

    const claim = await getClaimById(claimId);

    if (!claim) {

      return NextResponse.json(
        { error: "Claim not found" },
        { status: 404 }
      );
    }

    // ==================================================
    // CALL FASTAPI
    // ==================================================

    const mlResponse = await fetch(
      "http://127.0.0.1:8000/predict",
      {
        method: "POST",

        headers: {
          "Content-Type": "application/json",
        },

        body: JSON.stringify({
          user_claim: claim.content,
        }),
      }
    );

    // ==================================================
    // FASTAPI ERROR
    // ==================================================

    if (!mlResponse.ok) {

      return NextResponse.json(
        { error: "ML API error" },
        { status: 500 }
      );
    }

    // ==================================================
    // GET PREDICTION
    // ==================================================

    const data = await mlResponse.json();

    const generatedTag = data.prediction;

    // ==================================================
    // TAG NORMALIZATION
    // ==================================================

	const TAG_MAPPING = {

		"credit_reporting":
		"Credit reporting, credit repair services, or other personal consumer reports",

		"credit_card":
		"Credit card or prepaid card",

		"prepaid_card":
		"Credit card or prepaid card",

		"payday_loan":
		"Payday loan, title loan, or personal loan",

		"virtual_currency":
		"Money transfer, virtual currency, or money service",
	};


	// ==================================================
	// NORMALIZE MODEL TAG
	// ==================================================

	const normalizedTag =
  		TAG_MAPPING[generatedTag.toLowerCase()] || generatedTag;


// ==================================================
// FIND ALLOWED TAG
// ==================================================

	const tag = ALLOWED_TAGS.find(
		(allowed) =>
		allowed.toLowerCase() === normalizedTag.toLowerCase()
	);

    if (!tag) {

      return NextResponse.json(
        { error: "Invalid tag generated by ML model" },
        { status: 500 }
      );
    }

    // ==================================================
    // SAVE TAG
    // ==================================================

    await setClaimTag(claimId, tag);

    // ==================================================
    // RESPONSE
    // ==================================================

    return NextResponse.json({ tag });

  } catch (error) {

    console.error("Auto-tag error:", error);

    return NextResponse.json(
      {
        error: error.message || "ML service error"
      },
      {
        status: 500
      }
    );
  }
}